### ISSUE TITLE
KIND endpoint in kubeconfig

### ISSUE THREAD

**Issue by dirien** [Trendyol/kink#16]
Hi,

I can't access the API server of my kind-cluster. In the kubeconfig, i get only the internal ip adress.

```yaml
- cluster:
    server: https://10.250.2.131:30063
  name: kind-kind-190634c5-9762-4762-bb0a-6e32700f49cc
contexts:
```

Is there somthing i do wrong?

`kink` is creating a svc from type `NodePort``

```shell
est                                                  NodePort    100.68.250.121   <none>        30001:30063/TCP                                 16m
```
